FROM mcr.microsoft.com/windows/servercore:ltsc2019

COPY estafette-extension-docker.exe C:/estafette-extension-docker.exe

ENV ESTAFETTE_LOG_FORMAT="console" \
    PATH="C:\dod;$PATH"

USER ContainerAdministrator

ENTRYPOINT ["C:/estafette-extension-docker.exe"]